---
- name: Setup HAProxy for honeypot
  hosts: all
  module_defaults:
    ssh: False

  tasks:
  # TODO: support for apt/yum
  - name: Install HAProxy
    apt:
      name: haproxy
      state: latest

  - name: Add HAProxy config file
    template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

  - name: Restart Haproxy
    service:
        name: haproxy
        state: restarted
